# Generated by Django 3.0 on 2021-08-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_categoria', to='categorias.Categorias'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
