# Generated by Django 3.0 on 2021-08-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeModel')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad_preguntas', models.IntegerField(default=0)),
            ],
            bases=('core.timemodel',),
        ),
    ]
