# Generated by Django 3.0 on 2021-08-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('preguntas', '0003_auto_20210821_1834'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
